# -*- coding: utf-8 -*-
"""WOA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fq-5Zk2eyjmRfC9w6ttj0MvkRMMGf5L2
"""

!pip install yfinance

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

stocks = ['AAPL','MSFT','GOOGL','AMZN','TSLA']

data = yf.download(stocks,start='2025-05-04',end='2026-02-24').xs('Close', level='Price', axis=1)

returns = data.pct_change().dropna()

mean_returns = returns.mean()

cov_matrix = returns.cov()

def portfolio_risk(weights, cov_matrix):
    return np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))

def whale_optimization(n_whales, n_iter, dim, cov_matrix):

    whales = np.random.rand(n_whales, dim)
    whales = whales / np.sum(whales, axis=1)[:, None]

    best_whale = whales[0]
    best_score = portfolio_risk(best_whale, cov_matrix)

    for t in range(n_iter):

        a = 2 - t * (2 / n_iter)

        for i in range(n_whales):

            r = np.random.rand()
            A = 2 * a * r - a
            C = 2 * r

            p = np.random.rand()

            if p < 0.5:

                if abs(A) < 1:
                    D = abs(C * best_whale - whales[i])
                    whales[i] = best_whale - A * D

                else:
                    rand_whale = whales[np.random.randint(0, n_whales)]
                    D = abs(C * rand_whale - whales[i])
                    whales[i] = rand_whale - A * D

            else:
                D = abs(best_whale - whales[i])
                b = 1
                l = np.random.uniform(-1,1)
                whales[i] = D * np.exp(b*l) * np.cos(2*np.pi*l) + best_whale

            # --- Start of improved NaN and zero sum handling ---
            # Ensure no NaNs or infs are introduced during position update
            if np.any(np.isnan(whales[i])) or np.any(np.isinf(whales[i])):
                whales[i] = np.random.rand(dim) # Re-initialize if invalid

            whales[i] = np.clip(whales[i], 1e-6, 1) # Clip values to stay within bounds

            sum_of_weights = np.sum(whales[i])

            # Prevent division by zero or very small numbers
            if sum_of_weights < 1e-10: # Check if sum is effectively zero
                whales[i] = np.random.rand(dim) # Re-initialize if sum is too small
                whales[i] = whales[i] / np.sum(whales[i]) # Normalize the re-initialized weights
            else:
                whales[i] = whales[i] / sum_of_weights # Normalize
            # --- End of improved NaN and zero sum handling ---

            score = portfolio_risk(whales[i], cov_matrix)

            if score < best_score:
                best_score = score
                best_whale = whales[i]

    return best_whale, best_score

best_weights, best_risk = whale_optimization(
    n_whales=30,
    n_iter=100,
    dim=len(stocks),
    cov_matrix=cov_matrix
)

portfolio = pd.DataFrame({
    'Stock':stocks,
    'Weight':best_weights
})

print("Optimal Portfolio Allocation:\n")
print(portfolio)

print("\nMinimum Risk:",best_risk)

print("Original best_weights before nan_to_num:", best_weights)
print("Sum of original best_weights:", np.sum(best_weights))

best_weights_processed = np.nan_to_num(best_weights, nan=0.0)

# Handle the case where all weights might be zero after nan_to_num
sum_after_nan_to_num = np.sum(best_weights_processed)
if sum_after_nan_to_num == 0:
    # If all weights are zero, assign equal weights to avoid division by zero
    # and to display a neutral pie chart, or handle as an error if appropriate for the domain.
    # For plotting, equal weights will prevent the ValueError.
    print("Warning: All weights are zero after NaN handling. Assigning equal weights for plotting.")
    best_weights_normalized = np.ones(len(stocks)) / len(stocks)
else:
    best_weights_normalized = best_weights_processed / sum_after_nan_to_num

print("Processed and Normalized best_weights:", best_weights_normalized)
print("Sum of processed and normalized best_weights:", np.sum(best_weights_normalized))

plt.figure(figsize=(8,6))
plt.pie(best_weights_normalized, labels=stocks, autopct='%1.2f%%')
plt.title('Optimal Portfolio Allocation (WOA)')
plt.show()

portfolio_return = np.dot(best_weights, mean_returns)

print("Expected Return:",portfolio_return)

plt.scatter(best_risk, portfolio_return)
plt.xlabel("Risk")
plt.ylabel("Return")
plt.title("Optimized Portfolio Risk vs Return")
plt.show()